theme: jekyll-theme-slate
title: Harnessing the Conditioning Sensorium for Improved Image Translation
description: |-
  Cooper Nederhood, Nick Kolkin, Deqing Fu, Jason Salavon
  
  
  University of Chicago
  
  
  Toyota Technological Institute at Chicago"
  
