theme: jekyll-theme-slate
title: Harnessing the Conditioning Sensorium for Improved Image Translation
description: 
  Cooper Nederhood, Nick Kolkin, Deqing Fu, Jason Salavon
  \n\n\n
  University of Chicago, Toyota Technological Institute at Chicago
