theme: jekyll-theme-slate
title: Harnessing the Conditioning Sensorium for Improved Image Translation
description: 
- |
  Cooper Nederhood <sup>1</sup>, Nick Kolkin <sup>1</sup>, Deqing Fu, Jason Salavon
  
  University of Chicago, Toyota Technological Institute at Chicago
  
project_title.font-size: 24px
