theme: jekyll-theme-slate
title: Harnessing the Conditioning Sensorium for Improved Image Translation
description: "|-
  Cooper Nederhood [^1^], Nick Kolkin [^2^], Deqing Fu [^1^], Jason Salavon [^1^]
  
  
  University of Chicago, Toyota Technological Institute at Chicago"
  
